---
name: Build & deploy

on: 
  push: 
    branches: main

jobs: 
  push: 
    runs-on: ubuntu-latest
    steps: 
      - uses: action/chevkout@v2
        name: Cache modules
      # - uses: actions/cache@v1
      #   id: yarn-cache
      #   with:
      #     path: node_modules
      #     key:${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      #       restore-keys: ${{ runner.os }}-yarn-
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        # with:
        #  args: --acl public-read --follw-symlinks --delete
        with:
          # AWS_BUCKET: ${{secrets.BUCKET}}
          aws-access-key-id: ${{ secrets.ACCESS }}
          aws-secret-access-key: ${{ secrets.SECRETS }}
          aws-region: us-east-2
      - run: aws s3 cp . s3://testbucketfromgituser --recursive
          
...

